force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <displayFormat>A{0000}</displayFormat>
    <label>Employee Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Manager_Employee_Id__c</fullName>
    <label>Manager Employee Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeTriggerSelector.cls
public class EmployeeTriggerSelector {
    public List<Employee__c> getEmployees(){
        return [Select Id, Name, Employee_Email__c, Employee_Id__c,Designation__c,Manager__c,
                Manager_Employee_Id__c,Mobile__c,Date_of_Joining__c from Employee__c
                where Name != null AND Employee_Email__c != NULL AND Employee_Id__c != NULL AND Designation__c != NULL
                AND Manager__c != NULL AND Mobile__c != NULL AND Date_of_Joining__c != NULL];
    }
    
    public Id getUserId(){
        return[Select id,Name from user where Name = 'test gaurav test' limit 1].Id;
    }
    
    public String getUserName(){
        return[Select id,Name from user where Name = 'test gaurav test' limit 1].Name;
    }
    
}