force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object will store the errors which occurred during the creating of the assignment of permissions to the users.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field stores the error message.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AssignPermissionOnUserCreationQueueable.cls
public class AssignPermissionOnUserCreationQueueable implements Queueable {
    private List<Id> userIds;
    
    public assignPermissionOnUserCreationQueueable(List<Id> userIds){
        this.userIds = userIds;
    }
    
    public void execute(QueueableContext ctx){
        PermissionSet ps = [Select id,Name from PermissionSet where Name = 'SalesUserPsl'];
        List<PermissionSetAssignment> assignmentList = new List<PermissionSetAssignment>();
        
        For(Id usrId : userIds){
            assignmentList.add(new PermissionSetAssignment(
                PermissionSetId = ps.Id,
                AssigneeId = usrId
            ));
        }
        
        if(assignmentList.size() > 0){
            Database.SaveResult[] saveResult = Database.insert(assignmentList,false);
            List<Error_Log__c> errorLogList = new List<Error_Log__c>();
            for(Database.SaveResult result : saveResult){
                if(!result.IsSuccess()){
                    for(Database.Error err : result.getErrors()){
                        errorLogList.add(new Error_Log__c(
                            Error_Message__c = err.getMessage()
                        ));
                    }
                }
            }
            
            if(errorLogList.size() > 0){
                insert errorLogList;
            }
                
        }
        
    }
}