force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object will store the errors which occurred during the creating of the assignment of permissions to the users.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field stores the error message.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RemovePermissionsWhenUserIsDeactivated.cls
public class RemovePermissionsWhenUserIsDeactivated {
    @future
    public static void updateUserPermissionsWhenInactive(List<Id> userIds){
        
        List<PermissionSetAssignment> assignmentList = [Select AssigneeId,PermissionSetId from PermissionSetAssignment where AssigneeId In:userIds];
        
        List<PermissionSetAssignment> assignmentListToDelete = new List<PermissionSetAssignment>();
        
        if(assignmentList.size() > 0){
            for(PermissionSetAssignment asn : assignmentList ){
                assignmentListToDelete.add(asn);
            }
        }
        
        if(assignmentListToDelete.size() > 0){
            Database.deleteResult[] deleteResults = Database.delete(assignmentListToDelete, false);
            List<Error_Log__c> errorLogList = new List<Error_Log__c>();
            for(Database.deleteResult result: deleteResults){
                if(!result.isSuccess()){
                    for(Database.Error err : result.getErrors() ){
                        errorLogList.add(new Error_Log__c(
                            Error_Message__c = err.getMessage()
                        ));
                    }
                }
            }
            if(errorLogList.size() > 0){
                insert errorLogList;
            }
            
        }
        
    }
    
}